// Vendored copy of Limehouse-Fam/projects/map/src/namedAreaExclusions/
// pointInPolygon.ts. That file is the canonical source (owned by the Map
// sync-job project, a genuinely separate Node repo/deployment from this
// one) — this copy exists only because LimeHQ (this repo) and Map (that
// repo) are two separate git repositories with no shared package today, so
// a plain relative import isn't possible. This is flagged in Tron's build
// report as a real gap against the "no duplicated security/validation
// logic" standing rule: the two copies WILL drift if one is edited without
// the other. Fixing that properly means extracting this into a small
// shared npm package (or a workspace) both repos depend on — infrastructure
// work, not a frontend change, so it's called out for Scotty/Neo rather
// than solved here. Do not edit this file's logic without also updating
// the canonical copy, and vice versa.
//
// Used by src/map/mapRoutes.ts for the named-area exclusion tool's live
// "preview what this boundary currently matches" feature.

export interface LatLng {
  lat: number;
  lng: number;
}

// Treats lng as x and lat as y — fine at the scale of a single Hampton
// Roads neighborhood; this is not meant to handle polygons that cross the
// antimeridian or span a large fraction of the globe.
export function isPointInPolygon(point: LatLng, polygon: LatLng[]): boolean {
  if (polygon.length < 3) {
    throw new Error(`A polygon needs at least 3 points to enclose any area; got ${polygon.length}.`);
  }

  let inside = false;
  for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
    const vertexI = polygon[i]!;
    const vertexJ = polygon[j]!;

    const intersects =
      vertexI.lat > point.lat !== vertexJ.lat > point.lat &&
      point.lng <
        ((vertexJ.lng - vertexI.lng) * (point.lat - vertexI.lat)) / (vertexJ.lat - vertexI.lat) +
          vertexI.lng;

    if (intersects) inside = !inside;
  }
  return inside;
}

// Validates a boundary as stored in map.named_area_exclusions.boundary
// (JSONB) or as submitted fresh from the drawing tool's POST body — the
// database CHECK constraints can only verify "is this valid JSON," not "is
// this a sane polygon," so that check lives here, same as in the canonical
// copy.
export function validateBoundary(value: unknown): LatLng[] {
  if (!Array.isArray(value)) {
    throw new Error("A boundary must be an array of {lat, lng} points.");
  }
  if (value.length < 3) {
    throw new Error(`A boundary needs at least 3 points to enclose any area; got ${value.length}.`);
  }

  return value.map((point, index) => {
    if (
      typeof point !== "object" ||
      point === null ||
      typeof (point as Record<string, unknown>).lat !== "number" ||
      typeof (point as Record<string, unknown>).lng !== "number"
    ) {
      throw new Error(`Boundary point at index ${index} is not a valid {lat, lng} pair.`);
    }
    const lat = (point as { lat: number }).lat;
    const lng = (point as { lng: number }).lng;
    if (lat < -90 || lat > 90 || lng < -180 || lng > 180) {
      throw new Error(`Boundary point at index ${index} has an out-of-range coordinate: (${lat}, ${lng}).`);
    }
    return { lat, lng };
  });
}
